testthread:
    pattern:  /
    defaults: { _controller: "mgateTestBundle:TestThread:index" }

testthread_show:
    pattern:  /{id}/show
    defaults: { _controller: "mgateTestBundle:TestThread:show" }

testthread_new:
    pattern:  /new
    defaults: { _controller: "mgateTestBundle:TestThread:new" }

testthread_create:
    pattern:  /create
    defaults: { _controller: "mgateTestBundle:TestThread:create" }
    requirements: { _method: post }

testthread_edit:
    pattern:  /{id}/edit
    defaults: { _controller: "mgateTestBundle:TestThread:edit" }

testthread_update:
    pattern:  /{id}/update
    defaults: { _controller: "mgateTestBundle:TestThread:update" }
    requirements: { _method: post }

testthread_delete:
    pattern:  /{id}/delete
    defaults: { _controller: "mgateTestBundle:TestThread:delete" }
    requirements: { _method: post }
