mgate_formation_modifier:
    pattern:  /formations/modifier/{id}
    defaults: { _controller: mgateFormationBundle:Formation:modifier }
    requirements:
        key: \d+
    
mgate_formation_ajouter:
    pattern:  /formations/ajouter
    defaults: { _controller: mgateFormationBundle:Formation:modifier, key : -1}
