parameters:
#    mgate_formation.example.class: mgate\FormationBundle\Example

services:
#    mgate_formation.example:
#        class: %mgate_formation.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
