mgateSuivi_etude_homepage:
    pattern:  /{page}
    defaults: {_controller: mgateSuiviBundle:Etude:index , page: 1}
    requirements:
      page : \d*
    
mgateSuivi_etude_ajouter:
    pattern: /etude/ajouter
    defaults: {_controller: mgateSuiviBundle:Etude:add}
    requirements:
        id: \d+

mgateSuivi_etude_voir:
    pattern:   /etude/{id}
    defaults: {_controller: mgateSuiviBundle:Etude:voir}
    requirements:
        id:  \d+

mgateSuivi_etude_modifier:
    pattern: /etude/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:Etude:modifier}
    requirements:
        id: \d+
        
mgateSuivi_etude_panel:
    pattern:  /panel/test
    defaults: {_controller: mgateSuiviBundle:Panel:test , page: 1}
    requirements:
      page : \d* 
       
mgateSuivi_etude_supprimer:
    pattern: /etude/supprimer/{id}
    defaults: {_controller: mgateSuiviBundle:Etude:delete}
    requirements:
        id: \d+
        
#mgateSuivi_ap_generer:
#    pattern: /ap/generer/{id}
#    defaults: {_controller: mgateSuiviBundle:Ap:generer}
#    requirements:
#        id: \d+  
        
mgateSuivi_ap_voir:
    pattern: /ap/voir/{id}
    defaults: {_controller: mgateSuiviBundle:Ap:voir}
    requirements:
        id: \d+

mgateSuivi_ap_rediger:
    pattern: /ap/rediger/{id}
    defaults: {_controller: mgateSuiviBundle:Ap:rediger}
    requirements:
        id: \d+

mgateSuivi_ap_suivi:
    pattern: /ap/suivi/{id}
    defaults: {_controller: mgateSuiviBundle:Ap:suivi}
    requirements:
        id: \d+
        
mgateSuivi_cc_rediger:
    pattern: /cc/rediger/{id}
    defaults: {_controller: mgateSuiviBundle:Cc:rediger}
    requirements:
        id: \d+ 

mgateSuivi_cc_voir:
    pattern: /cc/voir/{id}
    defaults: {_controller: mgateSuiviBundle:Cc:voir}
    requirements:
        id: \d+
       
#mgateSuivi_cc_generer:
#    pattern: /cc/generer/{id}
#    defaults: {_controller: mgateSuiviBundle:Cc:generer}
#    requirements:
#        id: \d+  
        
mgateSuivi_cc_suivi:
    pattern: /cc/suivi/{id}
    defaults: {_controller: mgateSuiviBundle:Cc:suivi}
    requirements:
        id: \d+   
    
        
mgateSuivi_mission_rediger:
    pattern: /mission/rediger/{id}
    defaults: {_controller: mgateSuiviBundle:Mission:rediger}
    requirements:
        id: \d+
        
mgateSuivi_missions_modifier:
    pattern: /missions/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:Missions:modifier}
    requirements:
        id: \d+

#AJOUT AJAX

mgateSuivi_mission_avancement:
    pattern: /missions/modifier/avancement/
    defaults: {_controller: mgateSuiviBundle:Mission:avancement}
    
mgateSuivi_state:
    pattern: /suivi/state/
    defaults: {_controller: mgateSuiviBundle:Etude:state}
        
#mgateSuivi_missions_generer:
#    pattern: /missions/generer/{id}
#    defaults: {_controller: mgateSuiviBundle:Missions:generer}
#    requirements:
#        id: \d+
       
mgateSuivi_missions_repartition:
    pattern: /missions/repartition/{id}
    defaults: {_controller: mgateSuiviBundle:MissionsRepartition:index}
    requirements:
        id: \d+        
        
mgateSuivi_suivi_ajouter:
    pattern: /suivi/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Suivi:add}
    requirements:
        id: \d+
        
mgateSuivi_suivi_voir:
    pattern: /suivi/voir/{id}
    defaults: {_controller: mgateSuiviBundle:Suivi:voir}
    requirements:
        id: \d+
        
mgateSuivi_suivi_modifier:
    pattern: /suivi/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:Suivi:modifier}
    requirements:
        id: \d+


mgateSuivi_clientcontact_ajouter:
    pattern: /clientcontact/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:ClientContact:add}
    requirements:
        id: \d+
        
mgateSuivi_clientcontact_modifier:
    pattern: /clientcontact/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:ClientContact:modifier}
    requirements:
        id: \d+
        
mgateSuivi_clientcontact_voir:
    pattern: /clientcontact/voir/{id}
    defaults: {_controller: mgateSuiviBundle:ClientContact:voir}
    requirements:
        id: \d+     
    
        
mgateSuivi_av_ajouter:
    pattern: /av/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Av:add}
    requirements:
        id: \d+
        
mgateSuivi_av_modifier:
    pattern: /av/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:Av:modifier}
    requirements:
        id: \d+
        
mgateSuivi_av_voir:
    pattern: /av/voir/{id}
    defaults: {_controller: mgateSuiviBundle:Av:voir}
    requirements:
        id: \d+
        
mgateSuivi_avmission_ajouter:
    pattern: /avmission/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:AvMission:add}
    requirements:
        id: \d+
        
        
mgateSuivi_avmission_voir:
    pattern: /avmission/voir/{id}
    defaults: {_controller: mgateSuiviBundle:AvMission:voir}
    requirements:
        id: \d+
        
        
mgateSuivi_avmission_modifier:
    pattern: /avmission/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:AvMission:modifier}
    requirements:
        id: \d+

mgateSuivi_facture_ajouter:
    pattern: /facture/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Facture:add}
    requirements:
        id: \d+
        
mgateSuivi_facture_modifier:
    pattern: /facture/modifier/{id_facture}
    defaults: {_controller: mgateSuiviBundle:Facture:modifier}
    requirements:
        id: \d+
        
mgateSuivi_facture_rediger:
    pattern: /facture/rediger/{id_etude}/{type}
    defaults: {_controller: mgateSuiviBundle:Facture:rediger}
    requirements:
        id: \d+
 
mgateSuivi_facture_voir:
    pattern: /facture/voir/{id}
    defaults: {_controller: mgateSuiviBundle:Facture:voir}
    requirements:
        id: \d+
        
mgateSuivi_facture_supprimer:
    pattern: /facture/supprimer/{id}
    defaults: {_controller: mgateSuiviBundle:Facture:delete}
    requirements:
        id: \d+
         
                
mgateSuivi_phases_modifier:
    pattern: /phases/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:Phases:modifier}
    requirements:
        id: \d+

mgateSuivi_procesverbal_ajouter:
    pattern: /procesverbal/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:ProcesVerbal:add}
    requirements:
        id: \d+
      
mgateSuivi_procesverbal_modifier:
    pattern: /procesverbal/modifier/{id_pv}
    defaults: {_controller: mgateSuiviBundle:ProcesVerbal:modifier}
    requirements:
        id: \d+
        
mgateSuivi_procesverbal_rediger:
    pattern: /procesverbal/rediger/{id_etude}/{type}
    defaults: {_controller: mgateSuiviBundle:ProcesVerbal:rediger}
    requirements:
        id: \d+
 
mgateSuivi_procesverbal_voir:
    pattern: /procesverbal/voir/{id}
    defaults: {_controller: mgateSuiviBundle:ProcesVerbal:voir}
    requirements:
        id: \d+
        
mgateSuivi_procesverbal_supprimer:
    pattern: /procesverbal/supprimer/{id_pv}
    defaults: {_controller: mgateSuiviBundle:ProcesVerbal:delete}
    requirements:
        id: \d+