mgateSuivi_etude_homepage:
    pattern:  /{page}
    defaults: {_controller: mgateSuiviBundle:Etude:index , page: 1}
    requirements:
      page : \d*
    
mgateSuivi_etude_ajouter:
    pattern: /etude/ajouter
    defaults: {_controller: mgateSuiviBundle:Etude:add}
    requirements:
        id: \d+

mgateSuivi_etude_voir:
    pattern:   /etude/{id}
    defaults: {_controller: mgateSuiviBundle:Etude:voir}
    requirements:
        id:  \d+

mgateSuivi_etude_modifier:
    pattern: /etude/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:Etude:modifier}
    requirements:
        id: \d+
        
mgateSuivi_etude_panel:
    pattern:  /panel/test
    defaults: {_controller: mgateSuiviBundle:Panel:test , page: 1}
    requirements:
      page : \d*
        
mgateSuivi_ap_ajouter:
    pattern: /ap/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Ap:add}
    requirements:
        id: \d+
        
mgateSuivi_cc_ajouter:
    pattern: /cc/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Cc:add}
    requirements:
        id: \d+        

mgateSuivi_mission_ajouter:
    pattern: /mission/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Mission:add}
    requirements:
        id: \d+
        
mgateSuivi_suivi_ajouter:
    pattern: /suivi/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Suivi:add}
    requirements:
        id: \d+


mgateSuivi_clientcontact_ajouter:
    pattern: /clientcontact/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:ClientContact:add}
    requirements:
        id: \d+
        
mgateSuivi_pvi_ajouter:
    pattern: /pvi/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Pvi:add}
    requirements:
        id: \d+
        
        
mgateSuivi_av_ajouter:
    pattern: /av/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Av:add}
    requirements:
        id: \d+
        
mgateSuivi_avmission_ajouter:
    pattern: /avmission/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:AvMission:add}
    requirements:
        id: \d+
        
mgateSuivi_facture_ajouter:
    pattern: /facture/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Facture:add}
    requirements:
        id: \d+

mgateSuivi_pvr_ajouter:
    pattern: /pvr/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Pvr:add}
    requirements:
        id: \d+
        
mgateSuivi_phase_ajouter:
    pattern: /phase/ajouter/{id}
    defaults: {_controller: mgateSuiviBundle:Phase:add}
    requirements:
        id: \d+
        
mgateSuivi_phases_modifier:
    pattern: /phases/modifier/{id}
    defaults: {_controller: mgateSuiviBundle:Phases:modifier}
    requirements:
        id: \d+

        