parameters:
    mgate.etude_manager.class: mgate\SuiviBundle\Manager\EtudeManager
    mgate.doctype_manager.class: mgate\SuiviBundle\Manager\DocTypeManager
    tva: 0.196

services:
    mgate.etude_manager:
        class: "%mgate.etude_manager.class%"
        arguments:
          - "@doctrine.orm.entity_manager"
          - "%tva%"
        tags:
            - { name: twig.extension }
    mgate.doctype_manager:
        class: "%mgate.doctype_manager.class%"
        arguments:
          - "@doctrine.orm.entity_manager"
          