parameters:
    mgate.etude_manager.class: mgate\SuiviBundle\Manager\EtudeManager
    tva: 0.196

services:
    mgate.etude_manager:
        class: "%mgate.etude_manager.class%"
        arguments:
          - "@doctrine.orm.entity_manager"
          - "%tva%"
