parameters:
#    mgate_suivi.example.class: mgate\SuiviBundle\Example

services:
#    mgate_suivi.example:
#        class: %mgate_suivi.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
