mgate_indicateurs_index:
    pattern:  /admin/indicateurs
    defaults: { _controller: mgateStatBundle:Indicateurs:index }

mgate_indicateurs_ajax_suivi:
    pattern:  /admin/indicateurs/etudes
    defaults: { _controller: mgateStatBundle:Indicateurs:ajax }
