mgate_stat_homepage:
    pattern:  /stat/
    defaults: { _controller: mgateStatBundle:Default:index }

mgate_stat_ca:
    pattern:  /stat/ca
    defaults: { _controller: mgateStatBundle:Default:ca }
