mgate_publi_homepage:
    pattern:  /hellooo/{name}
    defaults: { _controller: mgatePubliBundle:Default:index }

 
mgate_publi_publiposter:
    pattern: /publi/publiposter/{id_etude}/{doc}/{key}
    defaults: {_controller: mgatePubliBundle:Traitement:publiposterEtude, key : -1}
    requirements:
        id_etude:  \d+
        key: \d+
        doc: AP|CC|FA|RM|PVR|PVI|FS|DM|FI
        #change tolower
    
mgate_publi_telecharger:
    pattern: /publi/publiposter/telecharger
    defaults: {_controller: mgatePubliBundle:Traitement:telecharger}
    
mgate_publi_documenttype_index:
    pattern: /publi/documenttype
    defaults: {_controller: mgatePubliBundle:DocumentType:index}
    
mgate_publi_documenttype_upload:
    pattern: /publi/documenttype/upload
    defaults: {_controller: mgatePubliBundle:DocumentType:upload}


mgate_publi_publiposter_eleve:
    pattern: /documents/telecharger/eleve/{id_eleve}/{doc}/{key}
    defaults: {_controller: mgatePubliBundle:Traitement:publiposterEleve, key : -1}
    requirements:
        id_eleve:  \d+
        key: \d+
        doc: AC|AA|CE