mgate_publi_homepage:
    pattern:  /hellooo/{name}
    defaults: { _controller: mgatePubliBundle:Default:index }

 
mgate_publi_publiposter:
    pattern: /publi/publiposter/{id_etude}/{doc}/{key}
    defaults: {_controller: mgatePubliBundle:Traitement:publiposter, key : -1}
    requirements:
        id_etude:  \d+
        key: \d+
        doc: AP|CC|FA|RM
    
mgate_publi_telecharger:
    pattern: /publi/publiposter/telecharger
    defaults: {_controller: mgatePubliBundle:Traitement:telecharger}
    
mgate_publi_documenttype_index:
    pattern: /publi/documenttype
    defaults: {_controller: mgatePubliBundle:DocumentType:index}
    
mgate_publi_documenttype_upload:
    pattern: /publi/documenttype/upload
    defaults: {_controller: mgatePubliBundle:DocumentType:upload}
