mgate_publi_homepage:
    pattern:  /hellooo/{name}
    defaults: { _controller: mgatePubliBundle:Default:index }


mgate_publi_publiposter:
    pattern: /publi/publiposter
    defaults: {_controller: mgatePubliBundle:Traitement:publiposter}
