parameters:
#    mgate_test.example.class: mgate\TestBundle\Example

services:
#    mgate_test.example:
#        class: %mgate_test.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
