mgate_treso_urssaf:
    pattern:  /urssaf
    defaults: { _controller: mgateTresoBundle:Urssaf:index }
    
mgateTreso_Compte_index:
    pattern:  /Compte
    defaults: { _controller: mgateTresoBundle:Compte:index }
        
mgateTreso_Compte_ajouter:
    pattern:  /Compte/Ajouter
    defaults: { _controller: mgateTresoBundle:Compte:modifier,  id:-1  }
    
mgateTreso_Compte_modifier:
    pattern:  /Compte/Modifier/{id}
    defaults: { _controller: mgateTresoBundle:Compte:modifier }
    requirements:
        id: \d+
    
mgateTreso_Compte_supprimer:
    pattern:  /Compte/Supprimer/{id}
    defaults: { _controller: mgateTresoBundle:Compte:supprimer }
    requirements:
        id: \d+    

mgateTreso_NoteDeFrais_index:
    pattern:  /NoteDeFrais
    defaults: { _controller: mgateTresoBundle:NoteDeFrais:index }
    
mgateTreso_NoteDeFrais_voir:
    pattern:  /NoteDeFrais/{id}
    defaults: { _controller: mgateTresoBundle:NoteDeFrais:voir }
    requirements:
        id: \d+
    
mgateTreso_NoteDeFrais_ajouter:
    pattern:  /NoteDeFrais/Ajouter
    defaults: { _controller: mgateTresoBundle:NoteDeFrais:modifier,  id:-1  }
    
mgateTreso_NoteDeFrais_modifier:
    pattern:  /NoteDeFrais/Modifier/{id}
    defaults: { _controller: mgateTresoBundle:NoteDeFrais:modifier }
    requirements:
        id: \d+
    
mgateTreso_NoteDeFrais_supprimer:
    pattern:  /NoteDeFrais/Supprimer/{id}
    defaults: { _controller: mgateTresoBundle:NoteDeFrais:supprimer }
    requirements:
        id: \d+

################################################################################
#                                                                              #
#                           BULLETIN DE VERSEMENT                              #
#                                                                              #
################################################################################
mgateTreso_BV_index:
    pattern:  /BV
    defaults: { _controller: mgateTresoBundle:BV:index }
        
mgateTreso_BV_ajouter:
    pattern:  /BV/Ajouter
    defaults: { _controller: mgateTresoBundle:BV:modifier,  id:-1  }
    
mgateTreso_BV_modifier:
    pattern:  /BV/Modifier/{id}
    defaults: { _controller: mgateTresoBundle:BV:modifier }
    requirements:
        id: \d+
    
mgateTreso_BV_supprimer:
    pattern:  /BV/Supprimer/{id}
    defaults: { _controller: mgateTresoBundle:BV:supprimer }
    requirements:
        id: \d+    
        
################################################################################
################################################################################
################################################################################