parameters:
#    mgate_treso.example.class: mgate\TresoBundle\Example

services:
#    mgate_treso.example:
#        class: %mgate_treso.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
